parameters:
#    arii_core.example.class: Arii\CoreBundle\Example
      
services: 

    arii_i5.exec:
        class: Arii\I5Bundle\Service\AriiExec
        arguments: [ "@arii_core.session", "@arii_core.audit","@arii_core.log" ]
